"""Long-term memory contracts and stores for proactive assistant."""

from proactive_assistant.memory.contracts import (
    MemoryContext,
    MemoryForgetResult,
    MemoryMergeAction,
    MemoryMergeDecision,
    MemoryPendingUpdate,
    MemoryPendingUpdateStatus,
    MemoryPromotionResult,
    MemoryPromotionStatus,
    MemoryQuery,
    MemoryRecord,
    MemoryRecordUpdate,
    MemoryRetrievalIntent,
    MemoryScope,
    MemorySearchResult,
    MemorySource,
    MemoryType,
    MemoryUpdatePolicyDecision,
    MemoryUpsertResult,
    MemoryUpsertStatus,
    MemoryUsePolicy,
    MemoryWriteStatus,
    RetentionPolicy,
)
from proactive_assistant.memory.compression import (
    MemoryCompressionModelOutput,
    MemoryCompressionRequest,
    MemoryCompressionResult,
    MemoryCompressionService,
)
from proactive_assistant.memory.extraction import (
    MemoryExtractionModelCandidate,
    MemoryExtractionModelOutput,
    MemoryExtractionRequest,
    MemoryExtractionResult,
    MemoryExtractionService,
)
from proactive_assistant.memory.evaluation import (
    MemoryExtractionCaseEvalResult,
    MemoryExtractionEvaluationReport,
    MemoryExtractionExpectedCandidate,
    MemoryExtractionFixtureCase,
    evaluate_memory_extraction_fixtures,
    load_memory_extraction_fixture_cases,
)
from proactive_assistant.memory.retrieval import MemoryRetriever, build_structured_query
from proactive_assistant.memory.service import MemoryService
from proactive_assistant.memory.snapshot import memory_candidates_from_meeting_state
from proactive_assistant.memory.store import (
    InMemoryMemoryStore,
    MemoryAlreadyExistsError,
    MemoryNotFoundError,
    MemoryRepository,
    MemoryStore,
    MemoryStoreError,
    MemoryPendingUpdateAlreadyExistsError,
    MemoryPendingUpdateNotFoundError,
)
from proactive_assistant.memory.vector_store import (
    InMemoryMemoryVectorStore,
    MemoryVectorRecord,
    MemoryVectorStore,
    cosine_similarity,
    memory_embedding_content_hash,
    memory_embedding_text,
)

__all__ = [
    "InMemoryMemoryStore",
    "InMemoryMemoryVectorStore",
    "MemoryAlreadyExistsError",
    "MemoryCompressionModelOutput",
    "MemoryCompressionRequest",
    "MemoryCompressionResult",
    "MemoryCompressionService",
    "MemoryContext",
    "MemoryExtractionModelCandidate",
    "MemoryExtractionModelOutput",
    "MemoryExtractionRequest",
    "MemoryExtractionResult",
    "MemoryExtractionService",
    "MemoryExtractionCaseEvalResult",
    "MemoryExtractionEvaluationReport",
    "MemoryExtractionExpectedCandidate",
    "MemoryExtractionFixtureCase",
    "MemoryForgetResult",
    "MemoryMergeAction",
    "MemoryMergeDecision",
    "MemoryPendingUpdate",
    "MemoryPendingUpdateStatus",
    "MemoryPendingUpdateAlreadyExistsError",
    "MemoryPendingUpdateNotFoundError",
    "MemoryPromotionResult",
    "MemoryPromotionStatus",
    "MemoryNotFoundError",
    "MemoryQuery",
    "MemoryRecord",
    "MemoryRecordUpdate",
    "MemoryRetrievalIntent",
    "MemoryRetriever",
    "MemoryRepository",
    "MemoryScope",
    "MemorySearchResult",
    "MemoryService",
    "MemorySource",
    "MemoryStore",
    "MemoryStoreError",
    "MemoryType",
    "MemoryUpdatePolicyDecision",
    "MemoryUpsertResult",
    "MemoryUpsertStatus",
    "MemoryUsePolicy",
    "MemoryVectorRecord",
    "MemoryVectorStore",
    "MemoryWriteStatus",
    "RetentionPolicy",
    "build_structured_query",
    "cosine_similarity",
    "evaluate_memory_extraction_fixtures",
    "load_memory_extraction_fixture_cases",
    "memory_embedding_content_hash",
    "memory_embedding_text",
    "memory_candidates_from_meeting_state",
]
