from __future__ import annotations

from time import perf_counter
from typing import Any

from proactive_assistant.prompting.contracts import (
    ContentGranularity,
    ModelUsageMetadata,
    PRDSurface,
    PrivacyLevel,
    PromptCategory,
    PromptGenerationRequest,
    PromptGenerationResult,
)


RULE_BASED_PROMPT_MODEL = "rule_prompt_generator_v0"


class RuleBasedPromptGenerationService:
    """Deterministic prompt generator for low-latency product fallback and rules-only mode."""

    def generate_prompt(
        self,
        request: PromptGenerationRequest,
        *,
        model: str | None = None,
    ) -> PromptGenerationResult:
        started = perf_counter()
        opportunity = _opportunity_context(request)
        category = _prompt_category(request, opportunity)
        if category is None:
            return _no_action_result(started, "no prompt category candidate")

        granularity = _content_granularity(request)
        privacy_level = _privacy_level(request, opportunity)
        privacy_risk = _privacy_risk(opportunity)
        captured_text = _captured_text(request, opportunity)
        source_refs = _source_refs(request, opportunity)
        memory_context = list(request.memory_context)

        if privacy_level == PrivacyLevel.HIGH or privacy_risk >= 0.7:
            title, glasses_text, detail = _privacy_safe_copy(category, captured_text, memory_context)
        elif category == PromptCategory.SUMMARY_GAP_CHECK:
            title, glasses_text, detail = _gap_check_copy(request, captured_text, memory_context)
        elif category == PromptCategory.SUGGESTION:
            title, glasses_text, detail = _suggestion_copy(captured_text, memory_context)
        elif category == PromptCategory.PERSON_OR_FACT:
            title, glasses_text, detail = _person_or_fact_copy(captured_text, memory_context)
        elif category == PromptCategory.CONCEPT_EXPLANATION:
            title, glasses_text, detail = _concept_copy(captured_text, memory_context)
        else:
            title, glasses_text, detail = _question_copy(captured_text, memory_context)

        if granularity == ContentGranularity.ICON_TITLE_ONLY:
            glasses_text = ""
        elif granularity == ContentGranularity.ONE_LINE_ANSWER:
            detail = detail or glasses_text
        elif granularity >= ContentGranularity.CONCISE_BULLETS:
            glasses_text = _shorten(glasses_text, 80)

        return PromptGenerationResult(
            should_prompt=True,
            prompt_category=category,
            content_granularity=granularity,
            glasses_title=title,
            glasses_text=glasses_text,
            app_detail_text=detail,
            source_refs=source_refs,
            confidence=_confidence(opportunity),
            privacy_level=privacy_level,
            privacy_risk=privacy_risk,
            rationale="generated by deterministic product rules",
            safety_flags=list(opportunity.get("safety_flags", [])),
            model_usage=ModelUsageMetadata(
                provider="rules",
                model=model or RULE_BASED_PROMPT_MODEL,
                latency_ms=int((perf_counter() - started) * 1000),
                cached=True,
            ),
        )


def _no_action_result(started: float, rationale: str) -> PromptGenerationResult:
    return PromptGenerationResult(
        should_prompt=False,
        prompt_category=None,
        content_granularity=ContentGranularity.NO_ACTION,
        glasses_title="",
        glasses_text="",
        app_detail_text="",
        source_refs=[],
        confidence=0.0,
        privacy_level=PrivacyLevel.LOW,
        privacy_risk=0.0,
        rationale=rationale,
        safety_flags=[],
        model_usage=ModelUsageMetadata(
            provider="rules",
            model=RULE_BASED_PROMPT_MODEL,
            latency_ms=int((perf_counter() - started) * 1000),
            cached=True,
        ),
    )


def _gap_check_copy(
    request: PromptGenerationRequest,
    captured_text: str,
    memory_context: list[str],
) -> tuple[str, str, str]:
    if request.prd_surface == PRDSurface.APP_SUMMARY_TAB:
        return (
            "会后查漏",
            "建议补齐负责人、截止时间、阻塞项和下一步。",
            _bullets(
                [
                    "确认每个行动项的负责人和截止时间。",
                    "标记还未达成一致的风险、依赖和阻塞项。",
                    "把待确认事项沉淀到总结或 Suggest。",
                    *_memory_bullets(memory_context),
                ]
            ),
        )
    missing = _gap_fields(captured_text)
    one_line = "建议确认：" + "、".join(missing) + "。"
    return (
        "待明确",
        one_line,
        _bullets(
            [
                f"捕捉到：{_shorten(captured_text, 120)}",
                f"建议立刻确认：{'、'.join(missing)}。",
                "若暂时无法定案，记录阻塞项和下一步跟进人。",
                *_memory_bullets(memory_context),
            ]
        ),
    )


def _suggestion_copy(captured_text: str, memory_context: list[str]) -> tuple[str, str, str]:
    return (
        "下一步建议",
        "先明确目标、风险和最小下一步。",
        _bullets(
            [
                f"当前问题：{_shorten(captured_text, 120)}",
                "建议先确认共同目标，再拆成一个可执行下一步。",
                "同步负责人、依赖方和需要升级的风险。",
                *_memory_bullets(memory_context),
            ]
        ),
    )


def _person_or_fact_copy(captured_text: str, memory_context: list[str]) -> tuple[str, str, str]:
    if memory_context:
        first_memory = _shorten(memory_context[0], 72)
        return (
            "可用记忆",
            f"相关记忆：{first_memory}",
            _bullets(
                [
                    f"当前问题：{_shorten(captured_text, 120)}",
                    *_memory_bullets(memory_context),
                    "建议基于已确认记忆回答，缺失事实再查证。",
                ]
            ),
        )
    return (
        "需要查证",
        "这是事实/历史信息问题，建议查证后回答。",
        _bullets(
            [
                f"当前问题：{_shorten(captured_text, 120)}",
                "规则层未找到可引用记忆，避免编造事实。",
                "可转入 APP 详情或等待 fact/LLM 服务补充。",
            ]
        ),
    )


def _concept_copy(captured_text: str, memory_context: list[str]) -> tuple[str, str, str]:
    return (
        "概念解释",
        "建议用一句定义加当前上下文解释。",
        _bullets(
            [
                f"捕捉到：{_shorten(captured_text, 120)}",
                "先给一句话定义，再说明它与当前议题的关系。",
                *_memory_bullets(memory_context),
            ]
        ),
    )


def _question_copy(captured_text: str, memory_context: list[str]) -> tuple[str, str, str]:
    return (
        "可追问",
        "建议先确认问题范围，再给简短回答。",
        _bullets(
            [
                f"捕捉到：{_shorten(captured_text, 120)}",
                "如果问题影响当前决策，建议立即澄清。",
                "如果只是背景信息，放入 APP 详情避免打断。",
                *_memory_bullets(memory_context),
            ]
        ),
    )


def _privacy_safe_copy(
    category: PromptCategory,
    captured_text: str,
    memory_context: list[str],
) -> tuple[str, str, str]:
    return (
        "敏感内容",
        "涉及敏感信息，建议在 APP 里查看。",
        _bullets(
            [
                f"类别：{category.value}",
                f"捕捉到：{_shorten(captured_text, 100)}",
                "眼镜端只保留低暴露提醒，详细内容转入 APP。",
                *_memory_bullets(memory_context[:2]),
            ]
        ),
    )


def _opportunity_context(request: PromptGenerationRequest) -> dict[str, Any]:
    value = request.session_context.get("opportunity", {})
    return value if isinstance(value, dict) else {}


def _prompt_category(
    request: PromptGenerationRequest,
    opportunity: dict[str, Any],
) -> PromptCategory | None:
    raw = opportunity.get("prompt_category") or request.prompt_category_candidate
    if raw is None:
        return None
    return PromptCategory(raw)


def _content_granularity(request: PromptGenerationRequest) -> ContentGranularity:
    value = ContentGranularity(request.target_content_granularity)
    if value == ContentGranularity.NO_ACTION:
        return ContentGranularity.ONE_LINE_ANSWER
    return value


def _privacy_level(request: PromptGenerationRequest, opportunity: dict[str, Any]) -> PrivacyLevel:
    raw = opportunity.get("privacy_level")
    if raw is not None:
        return PrivacyLevel(raw)
    if request.privacy_constraints:
        return PrivacyLevel.MEDIUM
    return PrivacyLevel.LOW


def _privacy_risk(opportunity: dict[str, Any]) -> float:
    raw = opportunity.get("privacy_risk", 0.12)
    return max(0.0, min(float(raw), 1.0))


def _confidence(opportunity: dict[str, Any]) -> float:
    raw = opportunity.get("detector_confidence", opportunity.get("confidence", 0.62))
    return max(0.0, min(float(raw), 1.0))


def _captured_text(request: PromptGenerationRequest, opportunity: dict[str, Any]) -> str:
    captured = opportunity.get("captured_text")
    if isinstance(captured, str) and captured.strip():
        return captured.strip()
    return request.transcript_window[-1].text


def _source_refs(request: PromptGenerationRequest, opportunity: dict[str, Any]) -> list[str]:
    ids = opportunity.get("trigger_segment_ids")
    if isinstance(ids, list) and ids:
        return [f"transcript:{item}" for item in ids if isinstance(item, str)]
    return [f"transcript:{item.transcript_id}" for item in request.transcript_window[-3:]]


def _gap_fields(text: str) -> list[str]:
    normalized = text.lower()
    fields: list[str] = []
    if any(term in normalized for term in ["谁负责", "负责人", "owner", "dri", "谁来做"]):
        fields.append("负责人")
    if any(term in normalized for term in ["截止", "deadline", "due date", "时间点"]):
        fields.append("截止时间")
    if any(term in normalized for term in ["风险", "阻塞", "blocker", "依赖"]):
        fields.append("风险/阻塞")
    if any(term in normalized for term in ["下一步", "action item", "待办", "跟进"]):
        fields.append("下一步")
    return fields or ["负责人", "截止时间", "下一步"]


def _memory_bullets(memory_context: list[str]) -> list[str]:
    return [f"参考记忆：{_shorten(item, 96)}" for item in memory_context[:3]]


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items if item)


def _shorten(text: str, limit: int) -> str:
    normalized = " ".join(text.split())
    if len(normalized) <= limit:
        return normalized
    return normalized[: max(0, limit - 1)].rstrip() + "…"
